#!/bin/bash
OUTFILE=out.psl
INFILES=
FLAGS=

# Find dplof
DPLOF=dplof
$DPLOF > /dev/null 2> /dev/null
if [ "$?" = "127" ]
then
    DPLOF="`dirname $0`"/dplof
fi

# Parse arguments
while [ "$1" ]
do
    if expr "$1" : '-' > /dev/null
    then
        # A flag
        if [ "$1" = "--output" -o "$1" = "-o" ]
        then
            shift
            OUTFILE="$1"

        else
            FLAGS="$FLAGS $1"

        fi

    elif expr "$1" : '.*\.psl$' > /dev/null
    then
        INFILES="$INFILES -s $1"

    elif expr "$1" : '.*\.plof$' > /dev/null
    then
        INFILES="$INFILES -i $1"

    else
        echo 'Unknown file type: '$1
        exit 1

    fi

    shift
done

echo $DPLOF $FLAGS $INFILES -c $OUTFILE
$DPLOF $FLAGS $INFILES -c $OUTFILE
exit $?
