#!/bin/bash

cd "`dirname $0`"/..
export PATH="`pwd`/cplof/src:$PATH"

runtest() {
    echo 'Running test '$1
    shift
    echo "$@"
    "$@"
    echo 'Result: '$?
}

for i in "$@"
do
    . autotests/"$i"
done
