#ifndef PLOF_PSL_H
#define PLOF_PSL_H

#define psl_push0     0x00
#define psl_push1     0x01
#define psl_push2     0x02
#define psl_push3     0x03
#define psl_push4     0x04
#define psl_push5     0x05
#define psl_push6     0x06
#define psl_push7     0x07
#define psl_pop       0x08
#define psl_this      0x09
#define psl_null      0x0A
#define psl_global    0x0B
#define psl_new       0x0C
#define psl_combine   0x0D
#define psl_member    0x0E
#define psl_memberset 0x0F
#define psl_parent    0x10
#define psl_parentset 0x11
#define psl_call      0x12
#define psl_return    0x13
#define psl_throw     0x14
#define psl_catch     0x15
#define psl_cmp       0x16
#define psl_concat    0x17
#define psl_wrap      0x18
#define psl_resolve   0x19
#define psl_loop      0x1A
#define psl_calli     0x1B
#define psl_replace   0x1C
#define psl_array     0x20
#define psl_aconcat   0x21
#define psl_length    0x22
#define psl_lengthset 0x23
#define psl_index     0x24
#define psl_indexset  0x25
#define psl_members   0x26
#define psl_rawlength 0x60
#define psl_slice     0x61
#define psl_rawcmp    0x62
#define psl_integer   0x70
#define psl_intwidth  0x71
#define psl_mul       0x72
#define psl_div       0x73
#define psl_mod       0x74
#define psl_add       0x76
#define psl_sub       0x77
#define psl_lt        0x78
#define psl_lte       0x79
#define psl_eq        0x7A
#define psl_ne        0x7B
#define psl_gt        0x7C
#define psl_gte       0x7D
#define psl_sl        0x7E
#define psl_sr        0x7F
#define psl_or        0x80
#define psl_nor       0x81
#define psl_xor       0x82
#define psl_nxor      0x83
#define psl_and       0x84
#define psl_nand      0x85
#define psl_byte      0x8E
#define psl_float     0x90
#define psl_fint      0x91
#define psl_fmul      0x92
#define psl_fdiv      0x93
#define psl_fmod      0x94
#define psl_fadd      0x96
#define psl_fsub      0x97
#define psl_flt       0x98
#define psl_flte      0x99
#define psl_feq       0x9A
#define psl_fne       0x9B
#define psl_fgt       0x9C
#define psl_fgte      0x9D
#define psl_version   0xC0
#define psl_dsrcfile  0xD0
#define psl_dsrcline  0xD1
#define psl_dsrccol   0xD2
#define psl_print     0xE0
#define psl_debug     0xE1
#define psl_trap      0xED
#define psl_include   0xEE
#define psl_parse     0xEF
#define psl_gadd      0xF0
#define psl_grem      0xF1
#define psl_gcommit   0xFB
#define psl_marker    0xFC
#define psl_immediate 0xFD
#define psl_code      0xFE
#define psl_raw       0xFF

#define psl_dlopen    0xC1
#define psl_dlclose   0xC2
#define psl_dlsym     0xC3
#define psl_cmalloc   0xC4
#define psl_cfree     0xC5
#define psl_cget      0xC6
#define psl_cset      0xC7
#define psl_ctype     0xC8
#define psl_cstruct   0xC9
#define psl_csizeof   0xCA
#define psl_csget     0xCB
#define psl_csset     0xCC
#define psl_prepcif   0xCD
#define psl_ccall     0xCE

#endif
