/*
 * Wrapper for generating particular files that need every PSL instruction
 *
 * Copyright (c) 2009 Gregor Richards
 * 
 * Permission is hereby granted, free of charge, to any person obtaining a copy
 * of this software and associated documentation files (the "Software"), to deal
 * in the Software without restriction, including without limitation the rights
 * to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
 * copies of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 * 
 * The above copyright notice and this permission notice shall be included in
 * all copies or substantial portions of the Software.
 * 
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 * AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 * OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
 * THE SOFTWARE.
 */

#include <stdio.h>

int main(int argc, char **argv)
{
    if (argc != 2) {
        fprintf(stderr, "Use: gen <file to gen>\n"
                        "Files supported: plof.vim psldasm-cmds.c psl-impl.c\n");
        return 1;
    }

    if (!strcmp(argv[1], "plof.vim")) {
        printf("syn keyword     pslKeyword      contained");
#define FOREACH(inst) \
        printf(" %s", #inst );
#include "psl_inst.h"
#undef FOREACH
        printf("\n");

    } else if (!strcmp(argv[1], "psldasm-cmds.c")) {
        printf("/* generated by gen.c */\n");
#define FOREACH(inst) \
        printf("case psl_%s:\nfprintf(out, \"%s\\n\");\nbreak;\n", #inst , #inst );
#include "psl_inst.h"
#undef FOREACH

    } else if (!strcmp(argv[1], "psl-impl.c")) {
        printf("/* generated by gen.c */\n");
#define FOREACH(inst) \
        printf("#include \"impl/%s.c\"\n", #inst );
#include "psl_inst.h"
#undef FOREACH

    } else {
        fprintf(stderr, "File %s unsupported.\n", argv[1]);
        return 1;

    }

    return 0;
}
