/* generated by gen.c */
case psl_push0:
    cpsl[cpsli] = addressof(interp_psl_push0);
#include "optim/push0.c"
    break;
case psl_push1:
    cpsl[cpsli] = addressof(interp_psl_push1);
#include "optim/push1.c"
    break;
case psl_push2:
    cpsl[cpsli] = addressof(interp_psl_push2);
#include "optim/push2.c"
    break;
case psl_push3:
    cpsl[cpsli] = addressof(interp_psl_push3);
#include "optim/push3.c"
    break;
case psl_push4:
    cpsl[cpsli] = addressof(interp_psl_push4);
#include "optim/push4.c"
    break;
case psl_push5:
    cpsl[cpsli] = addressof(interp_psl_push5);
#include "optim/push5.c"
    break;
case psl_push6:
    cpsl[cpsli] = addressof(interp_psl_push6);
#include "optim/push6.c"
    break;
case psl_push7:
    cpsl[cpsli] = addressof(interp_psl_push7);
#include "optim/push7.c"
    break;
case psl_pop:
    cpsl[cpsli] = addressof(interp_psl_pop);
#include "optim/pop.c"
    break;
case psl_this:
    cpsl[cpsli] = addressof(interp_psl_this);
#include "optim/this.c"
    break;
case psl_null:
    cpsl[cpsli] = addressof(interp_psl_null);
#include "optim/null.c"
    break;
case psl_global:
    cpsl[cpsli] = addressof(interp_psl_global);
#include "optim/global.c"
    break;
case psl_new:
    cpsl[cpsli] = addressof(interp_psl_new);
#include "optim/new.c"
    break;
case psl_combine:
    cpsl[cpsli] = addressof(interp_psl_combine);
#include "optim/combine.c"
    break;
case psl_member:
    cpsl[cpsli] = addressof(interp_psl_member);
#include "optim/member.c"
    break;
case psl_memberset:
    cpsl[cpsli] = addressof(interp_psl_memberset);
#include "optim/memberset.c"
    break;
case psl_parent:
    cpsl[cpsli] = addressof(interp_psl_parent);
#include "optim/parent.c"
    break;
case psl_parentset:
    cpsl[cpsli] = addressof(interp_psl_parentset);
#include "optim/parentset.c"
    break;
case psl_call:
    cpsl[cpsli] = addressof(interp_psl_call);
#include "optim/call.c"
    break;
case psl_return:
    cpsl[cpsli] = addressof(interp_psl_return);
#include "optim/return.c"
    break;
case psl_throw:
    cpsl[cpsli] = addressof(interp_psl_throw);
#include "optim/throw.c"
    break;
case psl_catch:
    cpsl[cpsli] = addressof(interp_psl_catch);
#include "optim/catch.c"
    break;
case psl_cmp:
    cpsl[cpsli] = addressof(interp_psl_cmp);
#include "optim/cmp.c"
    break;
case psl_concat:
    cpsl[cpsli] = addressof(interp_psl_concat);
#include "optim/concat.c"
    break;
case psl_wrap:
    cpsl[cpsli] = addressof(interp_psl_wrap);
#include "optim/wrap.c"
    break;
case psl_resolve:
    cpsl[cpsli] = addressof(interp_psl_resolve);
#include "optim/resolve.c"
    break;
case psl_while:
    cpsl[cpsli] = addressof(interp_psl_while);
#include "optim/while.c"
    break;
case psl_calli:
    cpsl[cpsli] = addressof(interp_psl_calli);
#include "optim/calli.c"
    break;
case psl_replace:
    cpsl[cpsli] = addressof(interp_psl_replace);
#include "optim/replace.c"
    break;
case psl_array:
    cpsl[cpsli] = addressof(interp_psl_array);
#include "optim/array.c"
    break;
case psl_aconcat:
    cpsl[cpsli] = addressof(interp_psl_aconcat);
#include "optim/aconcat.c"
    break;
case psl_length:
    cpsl[cpsli] = addressof(interp_psl_length);
#include "optim/length.c"
    break;
case psl_lengthset:
    cpsl[cpsli] = addressof(interp_psl_lengthset);
#include "optim/lengthset.c"
    break;
case psl_index:
    cpsl[cpsli] = addressof(interp_psl_index);
#include "optim/index.c"
    break;
case psl_indexset:
    cpsl[cpsli] = addressof(interp_psl_indexset);
#include "optim/indexset.c"
    break;
case psl_members:
    cpsl[cpsli] = addressof(interp_psl_members);
#include "optim/members.c"
    break;
case psl_rawlength:
    cpsl[cpsli] = addressof(interp_psl_rawlength);
#include "optim/rawlength.c"
    break;
case psl_slice:
    cpsl[cpsli] = addressof(interp_psl_slice);
#include "optim/slice.c"
    break;
case psl_rawcmp:
    cpsl[cpsli] = addressof(interp_psl_rawcmp);
#include "optim/rawcmp.c"
    break;
case psl_extractraw:
    cpsl[cpsli] = addressof(interp_psl_extractraw);
#include "optim/extractraw.c"
    break;
case psl_integer:
    cpsl[cpsli] = addressof(interp_psl_integer);
#include "optim/integer.c"
    break;
case psl_intwidth:
    cpsl[cpsli] = addressof(interp_psl_intwidth);
#include "optim/intwidth.c"
    break;
case psl_mul:
    cpsl[cpsli] = addressof(interp_psl_mul);
#include "optim/mul.c"
    break;
case psl_div:
    cpsl[cpsli] = addressof(interp_psl_div);
#include "optim/div.c"
    break;
case psl_mod:
    cpsl[cpsli] = addressof(interp_psl_mod);
#include "optim/mod.c"
    break;
case psl_add:
    cpsl[cpsli] = addressof(interp_psl_add);
#include "optim/add.c"
    break;
case psl_sub:
    cpsl[cpsli] = addressof(interp_psl_sub);
#include "optim/sub.c"
    break;
case psl_lt:
    cpsl[cpsli] = addressof(interp_psl_lt);
#include "optim/lt.c"
    break;
case psl_lte:
    cpsl[cpsli] = addressof(interp_psl_lte);
#include "optim/lte.c"
    break;
case psl_eq:
    cpsl[cpsli] = addressof(interp_psl_eq);
#include "optim/eq.c"
    break;
case psl_ne:
    cpsl[cpsli] = addressof(interp_psl_ne);
#include "optim/ne.c"
    break;
case psl_gt:
    cpsl[cpsli] = addressof(interp_psl_gt);
#include "optim/gt.c"
    break;
case psl_gte:
    cpsl[cpsli] = addressof(interp_psl_gte);
#include "optim/gte.c"
    break;
case psl_sl:
    cpsl[cpsli] = addressof(interp_psl_sl);
#include "optim/sl.c"
    break;
case psl_sr:
    cpsl[cpsli] = addressof(interp_psl_sr);
#include "optim/sr.c"
    break;
case psl_or:
    cpsl[cpsli] = addressof(interp_psl_or);
#include "optim/or.c"
    break;
case psl_nor:
    cpsl[cpsli] = addressof(interp_psl_nor);
#include "optim/nor.c"
    break;
case psl_xor:
    cpsl[cpsli] = addressof(interp_psl_xor);
#include "optim/xor.c"
    break;
case psl_nxor:
    cpsl[cpsli] = addressof(interp_psl_nxor);
#include "optim/nxor.c"
    break;
case psl_and:
    cpsl[cpsli] = addressof(interp_psl_and);
#include "optim/and.c"
    break;
case psl_nand:
    cpsl[cpsli] = addressof(interp_psl_nand);
#include "optim/nand.c"
    break;
case psl_byte:
    cpsl[cpsli] = addressof(interp_psl_byte);
#include "optim/byte.c"
    break;
case psl_float:
    cpsl[cpsli] = addressof(interp_psl_float);
#include "optim/float.c"
    break;
case psl_fint:
    cpsl[cpsli] = addressof(interp_psl_fint);
#include "optim/fint.c"
    break;
case psl_fmul:
    cpsl[cpsli] = addressof(interp_psl_fmul);
#include "optim/fmul.c"
    break;
case psl_fdiv:
    cpsl[cpsli] = addressof(interp_psl_fdiv);
#include "optim/fdiv.c"
    break;
case psl_fmod:
    cpsl[cpsli] = addressof(interp_psl_fmod);
#include "optim/fmod.c"
    break;
case psl_fadd:
    cpsl[cpsli] = addressof(interp_psl_fadd);
#include "optim/fadd.c"
    break;
case psl_fsub:
    cpsl[cpsli] = addressof(interp_psl_fsub);
#include "optim/fsub.c"
    break;
case psl_flt:
    cpsl[cpsli] = addressof(interp_psl_flt);
#include "optim/flt.c"
    break;
case psl_flte:
    cpsl[cpsli] = addressof(interp_psl_flte);
#include "optim/flte.c"
    break;
case psl_feq:
    cpsl[cpsli] = addressof(interp_psl_feq);
#include "optim/feq.c"
    break;
case psl_fne:
    cpsl[cpsli] = addressof(interp_psl_fne);
#include "optim/fne.c"
    break;
case psl_fgt:
    cpsl[cpsli] = addressof(interp_psl_fgt);
#include "optim/fgt.c"
    break;
case psl_fgte:
    cpsl[cpsli] = addressof(interp_psl_fgte);
#include "optim/fgte.c"
    break;
case psl_version:
    cpsl[cpsli] = addressof(interp_psl_version);
#include "optim/version.c"
    break;
case psl_dsrcfile:
    cpsl[cpsli] = addressof(interp_psl_dsrcfile);
#include "optim/dsrcfile.c"
    break;
case psl_dsrcline:
    cpsl[cpsli] = addressof(interp_psl_dsrcline);
#include "optim/dsrcline.c"
    break;
case psl_dsrccol:
    cpsl[cpsli] = addressof(interp_psl_dsrccol);
#include "optim/dsrccol.c"
    break;
case psl_print:
    cpsl[cpsli] = addressof(interp_psl_print);
#include "optim/print.c"
    break;
case psl_debug:
    cpsl[cpsli] = addressof(interp_psl_debug);
#include "optim/debug.c"
    break;
case psl_intrinsic:
    cpsl[cpsli] = addressof(interp_psl_intrinsic);
#include "optim/intrinsic.c"
    break;
case psl_trap:
    cpsl[cpsli] = addressof(interp_psl_trap);
#include "optim/trap.c"
    break;
case psl_include:
    cpsl[cpsli] = addressof(interp_psl_include);
#include "optim/include.c"
    break;
case psl_parse:
    cpsl[cpsli] = addressof(interp_psl_parse);
#include "optim/parse.c"
    break;
case psl_gadd:
    cpsl[cpsli] = addressof(interp_psl_gadd);
#include "optim/gadd.c"
    break;
case psl_grem:
    cpsl[cpsli] = addressof(interp_psl_grem);
#include "optim/grem.c"
    break;
case psl_gcommit:
    cpsl[cpsli] = addressof(interp_psl_gcommit);
#include "optim/gcommit.c"
    break;
case psl_marker:
    cpsl[cpsli] = addressof(interp_psl_marker);
#include "optim/marker.c"
    break;
case psl_immediate:
    cpsl[cpsli] = addressof(interp_psl_immediate);
#include "optim/immediate.c"
    break;
case psl_code:
    cpsl[cpsli] = addressof(interp_psl_code);
#include "optim/code.c"
    break;
case psl_raw:
    cpsl[cpsli] = addressof(interp_psl_raw);
#include "optim/raw.c"
    break;
case psl_dlopen:
    cpsl[cpsli] = addressof(interp_psl_dlopen);
#include "optim/dlopen.c"
    break;
case psl_dlclose:
    cpsl[cpsli] = addressof(interp_psl_dlclose);
#include "optim/dlclose.c"
    break;
case psl_dlsym:
    cpsl[cpsli] = addressof(interp_psl_dlsym);
#include "optim/dlsym.c"
    break;
case psl_cget:
    cpsl[cpsli] = addressof(interp_psl_cget);
#include "optim/cget.c"
    break;
case psl_cset:
    cpsl[cpsli] = addressof(interp_psl_cset);
#include "optim/cset.c"
    break;
case psl_cinteger:
    cpsl[cpsli] = addressof(interp_psl_cinteger);
#include "optim/cinteger.c"
    break;
case psl_ctype:
    cpsl[cpsli] = addressof(interp_psl_ctype);
#include "optim/ctype.c"
    break;
case psl_cstruct:
    cpsl[cpsli] = addressof(interp_psl_cstruct);
#include "optim/cstruct.c"
    break;
case psl_csizeof:
    cpsl[cpsli] = addressof(interp_psl_csizeof);
#include "optim/csizeof.c"
    break;
case psl_csget:
    cpsl[cpsli] = addressof(interp_psl_csget);
#include "optim/csget.c"
    break;
case psl_csset:
    cpsl[cpsli] = addressof(interp_psl_csset);
#include "optim/csset.c"
    break;
case psl_prepcif:
    cpsl[cpsli] = addressof(interp_psl_prepcif);
#include "optim/prepcif.c"
    break;
case psl_ccall:
    cpsl[cpsli] = addressof(interp_psl_ccall);
#include "optim/ccall.c"
    break;
