/* generated by gen.c */
case psl_push0:
    cpsl[cpsli] = addressof(interp_psl_push0);
#include "leaky/push0.c"
    break;
case psl_push1:
    cpsl[cpsli] = addressof(interp_psl_push1);
#include "leaky/push1.c"
    break;
case psl_push2:
    cpsl[cpsli] = addressof(interp_psl_push2);
#include "leaky/push2.c"
    break;
case psl_push3:
    cpsl[cpsli] = addressof(interp_psl_push3);
#include "leaky/push3.c"
    break;
case psl_push4:
    cpsl[cpsli] = addressof(interp_psl_push4);
#include "leaky/push4.c"
    break;
case psl_push5:
    cpsl[cpsli] = addressof(interp_psl_push5);
#include "leaky/push5.c"
    break;
case psl_push6:
    cpsl[cpsli] = addressof(interp_psl_push6);
#include "leaky/push6.c"
    break;
case psl_push7:
    cpsl[cpsli] = addressof(interp_psl_push7);
#include "leaky/push7.c"
    break;
case psl_pop:
    cpsl[cpsli] = addressof(interp_psl_pop);
#include "leaky/pop.c"
    break;
case psl_this:
    cpsl[cpsli] = addressof(interp_psl_this);
#include "leaky/this.c"
    break;
case psl_null:
    cpsl[cpsli] = addressof(interp_psl_null);
#include "leaky/null.c"
    break;
case psl_global:
    cpsl[cpsli] = addressof(interp_psl_global);
#include "leaky/global.c"
    break;
case psl_new:
    cpsl[cpsli] = addressof(interp_psl_new);
#include "leaky/new.c"
    break;
case psl_combine:
    cpsl[cpsli] = addressof(interp_psl_combine);
#include "leaky/combine.c"
    break;
case psl_member:
    cpsl[cpsli] = addressof(interp_psl_member);
#include "leaky/member.c"
    break;
case psl_memberset:
    cpsl[cpsli] = addressof(interp_psl_memberset);
#include "leaky/memberset.c"
    break;
case psl_parent:
    cpsl[cpsli] = addressof(interp_psl_parent);
#include "leaky/parent.c"
    break;
case psl_parentset:
    cpsl[cpsli] = addressof(interp_psl_parentset);
#include "leaky/parentset.c"
    break;
case psl_call:
    cpsl[cpsli] = addressof(interp_psl_call);
#include "leaky/call.c"
    break;
case psl_return:
    cpsl[cpsli] = addressof(interp_psl_return);
#include "leaky/return.c"
    break;
case psl_throw:
    cpsl[cpsli] = addressof(interp_psl_throw);
#include "leaky/throw.c"
    break;
case psl_catch:
    cpsl[cpsli] = addressof(interp_psl_catch);
#include "leaky/catch.c"
    break;
case psl_cmp:
    cpsl[cpsli] = addressof(interp_psl_cmp);
#include "leaky/cmp.c"
    break;
case psl_concat:
    cpsl[cpsli] = addressof(interp_psl_concat);
#include "leaky/concat.c"
    break;
case psl_wrap:
    cpsl[cpsli] = addressof(interp_psl_wrap);
#include "leaky/wrap.c"
    break;
case psl_resolve:
    cpsl[cpsli] = addressof(interp_psl_resolve);
#include "leaky/resolve.c"
    break;
case psl_while:
    cpsl[cpsli] = addressof(interp_psl_while);
#include "leaky/while.c"
    break;
case psl_calli:
    cpsl[cpsli] = addressof(interp_psl_calli);
#include "leaky/calli.c"
    break;
case psl_replace:
    cpsl[cpsli] = addressof(interp_psl_replace);
#include "leaky/replace.c"
    break;
case psl_array:
    cpsl[cpsli] = addressof(interp_psl_array);
#include "leaky/array.c"
    break;
case psl_aconcat:
    cpsl[cpsli] = addressof(interp_psl_aconcat);
#include "leaky/aconcat.c"
    break;
case psl_length:
    cpsl[cpsli] = addressof(interp_psl_length);
#include "leaky/length.c"
    break;
case psl_lengthset:
    cpsl[cpsli] = addressof(interp_psl_lengthset);
#include "leaky/lengthset.c"
    break;
case psl_index:
    cpsl[cpsli] = addressof(interp_psl_index);
#include "leaky/index.c"
    break;
case psl_indexset:
    cpsl[cpsli] = addressof(interp_psl_indexset);
#include "leaky/indexset.c"
    break;
case psl_members:
    cpsl[cpsli] = addressof(interp_psl_members);
#include "leaky/members.c"
    break;
case psl_rawlength:
    cpsl[cpsli] = addressof(interp_psl_rawlength);
#include "leaky/rawlength.c"
    break;
case psl_slice:
    cpsl[cpsli] = addressof(interp_psl_slice);
#include "leaky/slice.c"
    break;
case psl_rawcmp:
    cpsl[cpsli] = addressof(interp_psl_rawcmp);
#include "leaky/rawcmp.c"
    break;
case psl_integer:
    cpsl[cpsli] = addressof(interp_psl_integer);
#include "leaky/integer.c"
    break;
case psl_intwidth:
    cpsl[cpsli] = addressof(interp_psl_intwidth);
#include "leaky/intwidth.c"
    break;
case psl_mul:
    cpsl[cpsli] = addressof(interp_psl_mul);
#include "leaky/mul.c"
    break;
case psl_div:
    cpsl[cpsli] = addressof(interp_psl_div);
#include "leaky/div.c"
    break;
case psl_mod:
    cpsl[cpsli] = addressof(interp_psl_mod);
#include "leaky/mod.c"
    break;
case psl_add:
    cpsl[cpsli] = addressof(interp_psl_add);
#include "leaky/add.c"
    break;
case psl_sub:
    cpsl[cpsli] = addressof(interp_psl_sub);
#include "leaky/sub.c"
    break;
case psl_lt:
    cpsl[cpsli] = addressof(interp_psl_lt);
#include "leaky/lt.c"
    break;
case psl_lte:
    cpsl[cpsli] = addressof(interp_psl_lte);
#include "leaky/lte.c"
    break;
case psl_eq:
    cpsl[cpsli] = addressof(interp_psl_eq);
#include "leaky/eq.c"
    break;
case psl_ne:
    cpsl[cpsli] = addressof(interp_psl_ne);
#include "leaky/ne.c"
    break;
case psl_gt:
    cpsl[cpsli] = addressof(interp_psl_gt);
#include "leaky/gt.c"
    break;
case psl_gte:
    cpsl[cpsli] = addressof(interp_psl_gte);
#include "leaky/gte.c"
    break;
case psl_sl:
    cpsl[cpsli] = addressof(interp_psl_sl);
#include "leaky/sl.c"
    break;
case psl_sr:
    cpsl[cpsli] = addressof(interp_psl_sr);
#include "leaky/sr.c"
    break;
case psl_or:
    cpsl[cpsli] = addressof(interp_psl_or);
#include "leaky/or.c"
    break;
case psl_nor:
    cpsl[cpsli] = addressof(interp_psl_nor);
#include "leaky/nor.c"
    break;
case psl_xor:
    cpsl[cpsli] = addressof(interp_psl_xor);
#include "leaky/xor.c"
    break;
case psl_nxor:
    cpsl[cpsli] = addressof(interp_psl_nxor);
#include "leaky/nxor.c"
    break;
case psl_and:
    cpsl[cpsli] = addressof(interp_psl_and);
#include "leaky/and.c"
    break;
case psl_nand:
    cpsl[cpsli] = addressof(interp_psl_nand);
#include "leaky/nand.c"
    break;
case psl_byte:
    cpsl[cpsli] = addressof(interp_psl_byte);
#include "leaky/byte.c"
    break;
case psl_float:
    cpsl[cpsli] = addressof(interp_psl_float);
#include "leaky/float.c"
    break;
case psl_fint:
    cpsl[cpsli] = addressof(interp_psl_fint);
#include "leaky/fint.c"
    break;
case psl_fmul:
    cpsl[cpsli] = addressof(interp_psl_fmul);
#include "leaky/fmul.c"
    break;
case psl_fdiv:
    cpsl[cpsli] = addressof(interp_psl_fdiv);
#include "leaky/fdiv.c"
    break;
case psl_fmod:
    cpsl[cpsli] = addressof(interp_psl_fmod);
#include "leaky/fmod.c"
    break;
case psl_fadd:
    cpsl[cpsli] = addressof(interp_psl_fadd);
#include "leaky/fadd.c"
    break;
case psl_fsub:
    cpsl[cpsli] = addressof(interp_psl_fsub);
#include "leaky/fsub.c"
    break;
case psl_flt:
    cpsl[cpsli] = addressof(interp_psl_flt);
#include "leaky/flt.c"
    break;
case psl_flte:
    cpsl[cpsli] = addressof(interp_psl_flte);
#include "leaky/flte.c"
    break;
case psl_feq:
    cpsl[cpsli] = addressof(interp_psl_feq);
#include "leaky/feq.c"
    break;
case psl_fne:
    cpsl[cpsli] = addressof(interp_psl_fne);
#include "leaky/fne.c"
    break;
case psl_fgt:
    cpsl[cpsli] = addressof(interp_psl_fgt);
#include "leaky/fgt.c"
    break;
case psl_fgte:
    cpsl[cpsli] = addressof(interp_psl_fgte);
#include "leaky/fgte.c"
    break;
case psl_version:
    cpsl[cpsli] = addressof(interp_psl_version);
#include "leaky/version.c"
    break;
case psl_dsrcfile:
    cpsl[cpsli] = addressof(interp_psl_dsrcfile);
#include "leaky/dsrcfile.c"
    break;
case psl_dsrcline:
    cpsl[cpsli] = addressof(interp_psl_dsrcline);
#include "leaky/dsrcline.c"
    break;
case psl_dsrccol:
    cpsl[cpsli] = addressof(interp_psl_dsrccol);
#include "leaky/dsrccol.c"
    break;
case psl_print:
    cpsl[cpsli] = addressof(interp_psl_print);
#include "leaky/print.c"
    break;
case psl_debug:
    cpsl[cpsli] = addressof(interp_psl_debug);
#include "leaky/debug.c"
    break;
case psl_trap:
    cpsl[cpsli] = addressof(interp_psl_trap);
#include "leaky/trap.c"
    break;
case psl_include:
    cpsl[cpsli] = addressof(interp_psl_include);
#include "leaky/include.c"
    break;
case psl_parse:
    cpsl[cpsli] = addressof(interp_psl_parse);
#include "leaky/parse.c"
    break;
case psl_gadd:
    cpsl[cpsli] = addressof(interp_psl_gadd);
#include "leaky/gadd.c"
    break;
case psl_grem:
    cpsl[cpsli] = addressof(interp_psl_grem);
#include "leaky/grem.c"
    break;
case psl_gcommit:
    cpsl[cpsli] = addressof(interp_psl_gcommit);
#include "leaky/gcommit.c"
    break;
case psl_marker:
    cpsl[cpsli] = addressof(interp_psl_marker);
#include "leaky/marker.c"
    break;
case psl_immediate:
    cpsl[cpsli] = addressof(interp_psl_immediate);
#include "leaky/immediate.c"
    break;
case psl_code:
    cpsl[cpsli] = addressof(interp_psl_code);
#include "leaky/code.c"
    break;
case psl_raw:
    cpsl[cpsli] = addressof(interp_psl_raw);
#include "leaky/raw.c"
    break;
case psl_dlopen:
    cpsl[cpsli] = addressof(interp_psl_dlopen);
#include "leaky/dlopen.c"
    break;
case psl_dlclose:
    cpsl[cpsli] = addressof(interp_psl_dlclose);
#include "leaky/dlclose.c"
    break;
case psl_dlsym:
    cpsl[cpsli] = addressof(interp_psl_dlsym);
#include "leaky/dlsym.c"
    break;
case psl_cget:
    cpsl[cpsli] = addressof(interp_psl_cget);
#include "leaky/cget.c"
    break;
case psl_cset:
    cpsl[cpsli] = addressof(interp_psl_cset);
#include "leaky/cset.c"
    break;
case psl_ctype:
    cpsl[cpsli] = addressof(interp_psl_ctype);
#include "leaky/ctype.c"
    break;
case psl_cstruct:
    cpsl[cpsli] = addressof(interp_psl_cstruct);
#include "leaky/cstruct.c"
    break;
case psl_csizeof:
    cpsl[cpsli] = addressof(interp_psl_csizeof);
#include "leaky/csizeof.c"
    break;
case psl_csget:
    cpsl[cpsli] = addressof(interp_psl_csget);
#include "leaky/csget.c"
    break;
case psl_csset:
    cpsl[cpsli] = addressof(interp_psl_csset);
#include "leaky/csset.c"
    break;
case psl_prepcif:
    cpsl[cpsli] = addressof(interp_psl_prepcif);
#include "leaky/prepcif.c"
    break;
case psl_ccall:
    cpsl[cpsli] = addressof(interp_psl_ccall);
#include "leaky/ccall.c"
    break;
