/*
 * A convenience header for repetetive code over every instruction
 *
 * Copyright (C) 2009 Gregor Richards
 * 
 * Permission is hereby granted, free of charge, to any person obtaining a copy
 * of this software and associated documentation files (the "Software"), to deal
 * in the Software without restriction, including without limitation the rights
 * to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
 * copies of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 * 
 * The above copyright notice and this permission notice shall be included in
 * all copies or substantial portions of the Software.
 * 
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 * AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 * OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
 * THE SOFTWARE.
 */

FOREACH(push0)
FOREACH(push1)
FOREACH(push2)
FOREACH(push3)
FOREACH(push4)
FOREACH(push5)
FOREACH(push6)
FOREACH(push7)
FOREACH(pop)
FOREACH(this)
FOREACH(null)
FOREACH(global)
FOREACH(new)
FOREACH(combine)
FOREACH(member)
FOREACH(memberset)
FOREACH(parent)
FOREACH(parentset)
FOREACH(call)
FOREACH(return)
FOREACH(throw)
FOREACH(catch)
FOREACH(cmp)
FOREACH(concat)
FOREACH(wrap)
FOREACH(resolve)
FOREACH(while)
FOREACH(calli)
FOREACH(replace)
FOREACH(array)
FOREACH(aconcat)
FOREACH(length)
FOREACH(lengthset)
FOREACH(index)
FOREACH(indexset)
FOREACH(members)
FOREACH(rawlength)
FOREACH(slice)
FOREACH(rawcmp)
FOREACH(extractraw)
FOREACH(integer)
FOREACH(intwidth)
FOREACH(mul)
FOREACH(div)
FOREACH(mod)
FOREACH(add)
FOREACH(sub)
FOREACH(lt)
FOREACH(lte)
FOREACH(eq)
FOREACH(ne)
FOREACH(gt)
FOREACH(gte)
FOREACH(sl)
FOREACH(sr)
FOREACH(or)
FOREACH(nor)
FOREACH(xor)
FOREACH(nxor)
FOREACH(and)
FOREACH(nand)
FOREACH(byte)
FOREACH(float)
FOREACH(fint)
FOREACH(fmul)
FOREACH(fdiv)
FOREACH(fmod)
FOREACH(fadd)
FOREACH(fsub)
FOREACH(flt)
FOREACH(flte)
FOREACH(feq)
FOREACH(fne)
FOREACH(fgt)
FOREACH(fgte)
FOREACH(version)
FOREACH(dsrcfile)
FOREACH(dsrcline)
FOREACH(dsrccol)
FOREACH(print)
FOREACH(debug)
FOREACH(intrinsic)
FOREACH(trap)
FOREACH(include)
FOREACH(parse)
FOREACH(gadd)
FOREACH(grem)
FOREACH(gcommit)
FOREACH(marker)
FOREACH(immediate)
FOREACH(code)
FOREACH(raw)
FOREACH(dlopen)
FOREACH(dlclose)
FOREACH(dlsym)
FOREACH(cget)
FOREACH(cset)
FOREACH(cinteger)
FOREACH(ctype)
FOREACH(cstruct)
FOREACH(csizeof)
FOREACH(csget)
FOREACH(csset)
FOREACH(prepcif)
FOREACH(ccall)
