/* generated by gen.c */
case psl_push0:
fprintf(out, "push0\n");
break;
case psl_push1:
fprintf(out, "push1\n");
break;
case psl_push2:
fprintf(out, "push2\n");
break;
case psl_push3:
fprintf(out, "push3\n");
break;
case psl_push4:
fprintf(out, "push4\n");
break;
case psl_push5:
fprintf(out, "push5\n");
break;
case psl_push6:
fprintf(out, "push6\n");
break;
case psl_push7:
fprintf(out, "push7\n");
break;
case psl_pop:
fprintf(out, "pop\n");
break;
case psl_this:
fprintf(out, "this\n");
break;
case psl_null:
fprintf(out, "null\n");
break;
case psl_global:
fprintf(out, "global\n");
break;
case psl_new:
fprintf(out, "new\n");
break;
case psl_combine:
fprintf(out, "combine\n");
break;
case psl_member:
fprintf(out, "member\n");
break;
case psl_memberset:
fprintf(out, "memberset\n");
break;
case psl_parent:
fprintf(out, "parent\n");
break;
case psl_parentset:
fprintf(out, "parentset\n");
break;
case psl_call:
fprintf(out, "call\n");
break;
case psl_return:
fprintf(out, "return\n");
break;
case psl_throw:
fprintf(out, "throw\n");
break;
case psl_catch:
fprintf(out, "catch\n");
break;
case psl_cmp:
fprintf(out, "cmp\n");
break;
case psl_concat:
fprintf(out, "concat\n");
break;
case psl_wrap:
fprintf(out, "wrap\n");
break;
case psl_resolve:
fprintf(out, "resolve\n");
break;
case psl_while:
fprintf(out, "while\n");
break;
case psl_calli:
fprintf(out, "calli\n");
break;
case psl_replace:
fprintf(out, "replace\n");
break;
case psl_array:
fprintf(out, "array\n");
break;
case psl_aconcat:
fprintf(out, "aconcat\n");
break;
case psl_length:
fprintf(out, "length\n");
break;
case psl_lengthset:
fprintf(out, "lengthset\n");
break;
case psl_index:
fprintf(out, "index\n");
break;
case psl_indexset:
fprintf(out, "indexset\n");
break;
case psl_members:
fprintf(out, "members\n");
break;
case psl_rawlength:
fprintf(out, "rawlength\n");
break;
case psl_slice:
fprintf(out, "slice\n");
break;
case psl_rawcmp:
fprintf(out, "rawcmp\n");
break;
case psl_integer:
fprintf(out, "integer\n");
break;
case psl_intwidth:
fprintf(out, "intwidth\n");
break;
case psl_mul:
fprintf(out, "mul\n");
break;
case psl_div:
fprintf(out, "div\n");
break;
case psl_mod:
fprintf(out, "mod\n");
break;
case psl_add:
fprintf(out, "add\n");
break;
case psl_sub:
fprintf(out, "sub\n");
break;
case psl_lt:
fprintf(out, "lt\n");
break;
case psl_lte:
fprintf(out, "lte\n");
break;
case psl_eq:
fprintf(out, "eq\n");
break;
case psl_ne:
fprintf(out, "ne\n");
break;
case psl_gt:
fprintf(out, "gt\n");
break;
case psl_gte:
fprintf(out, "gte\n");
break;
case psl_sl:
fprintf(out, "sl\n");
break;
case psl_sr:
fprintf(out, "sr\n");
break;
case psl_or:
fprintf(out, "or\n");
break;
case psl_nor:
fprintf(out, "nor\n");
break;
case psl_xor:
fprintf(out, "xor\n");
break;
case psl_nxor:
fprintf(out, "nxor\n");
break;
case psl_and:
fprintf(out, "and\n");
break;
case psl_nand:
fprintf(out, "nand\n");
break;
case psl_byte:
fprintf(out, "byte\n");
break;
case psl_float:
fprintf(out, "float\n");
break;
case psl_fint:
fprintf(out, "fint\n");
break;
case psl_fmul:
fprintf(out, "fmul\n");
break;
case psl_fdiv:
fprintf(out, "fdiv\n");
break;
case psl_fmod:
fprintf(out, "fmod\n");
break;
case psl_fadd:
fprintf(out, "fadd\n");
break;
case psl_fsub:
fprintf(out, "fsub\n");
break;
case psl_flt:
fprintf(out, "flt\n");
break;
case psl_flte:
fprintf(out, "flte\n");
break;
case psl_feq:
fprintf(out, "feq\n");
break;
case psl_fne:
fprintf(out, "fne\n");
break;
case psl_fgt:
fprintf(out, "fgt\n");
break;
case psl_fgte:
fprintf(out, "fgte\n");
break;
case psl_version:
fprintf(out, "version\n");
break;
case psl_dsrcfile:
fprintf(out, "dsrcfile\n");
break;
case psl_dsrcline:
fprintf(out, "dsrcline\n");
break;
case psl_dsrccol:
fprintf(out, "dsrccol\n");
break;
case psl_print:
fprintf(out, "print\n");
break;
case psl_debug:
fprintf(out, "debug\n");
break;
case psl_intrinsic:
fprintf(out, "intrinsic\n");
break;
case psl_trap:
fprintf(out, "trap\n");
break;
case psl_include:
fprintf(out, "include\n");
break;
case psl_parse:
fprintf(out, "parse\n");
break;
case psl_gadd:
fprintf(out, "gadd\n");
break;
case psl_grem:
fprintf(out, "grem\n");
break;
case psl_gcommit:
fprintf(out, "gcommit\n");
break;
case psl_marker:
fprintf(out, "marker\n");
break;
case psl_immediate:
fprintf(out, "immediate\n");
break;
case psl_code:
fprintf(out, "code\n");
break;
case psl_raw:
fprintf(out, "raw\n");
break;
case psl_dlopen:
fprintf(out, "dlopen\n");
break;
case psl_dlclose:
fprintf(out, "dlclose\n");
break;
case psl_dlsym:
fprintf(out, "dlsym\n");
break;
case psl_cget:
fprintf(out, "cget\n");
break;
case psl_cset:
fprintf(out, "cset\n");
break;
case psl_cinteger:
fprintf(out, "cinteger\n");
break;
case psl_ctype:
fprintf(out, "ctype\n");
break;
case psl_cstruct:
fprintf(out, "cstruct\n");
break;
case psl_csizeof:
fprintf(out, "csizeof\n");
break;
case psl_csget:
fprintf(out, "csget\n");
break;
case psl_csset:
fprintf(out, "csset\n");
break;
case psl_prepcif:
fprintf(out, "prepcif\n");
break;
case psl_ccall:
fprintf(out, "ccall\n");
break;
